# Generated by Django 2.2.10 on 2020-02-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0002_auto_20200219_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='appconfig',
            name='auth_users',
            field=models.CharField(blank=True, default='261336294 448374494', help_text='chat where the records will be stored', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='api_hash',
            field=models.CharField(blank=True, default=None, help_text='getting from https://my.telegram.org/auth', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='api_id',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='getting from https://my.telegram.org/auth', null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='non active config is not working', null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='is_bot',
            field=models.BooleanField(default=None, help_text='select if you want to use bot account for this config', null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='posting_channel',
            field=models.CharField(blank=True, default='-1001317892207', help_text='channel where the recordings will be published', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='temp_chat',
            field=models.CharField(blank=True, default='@postoronniy_bot', help_text='chat where the records will be stored', max_length=255, null=True),
        ),
    ]
