# Generated by Django 2.2.7 on 2020-02-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20191130_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('yt_id', models.TextField(primary_key=True, serialize=False, verbose_name='Id видео')),
                ('yt_url', models.URLField(verbose_name='Ссылка на видео')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения')),
                ('title', models.TextField(verbose_name='Название видео')),
                ('uploader', models.TextField(verbose_name='Канал отправителя')),
                ('upload_date', models.DateField(verbose_name='Дата публикации')),
                ('view_count', models.PositiveIntegerField(verbose_name='Просмотров')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('tg_id', models.TextField(verbose_name='Id в телеграме')),
            ],
            options={
                'verbose_name': 'Видео',
                'verbose_name_plural': 'Видео',
            },
        ),
    ]
