# Generated by Django 2.2.10 on 2020-02-21 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0003_auto_20200219_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_url', models.URLField(verbose_name='Ссылка на плейлист')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='Последняя проверка')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
        migrations.AlterModelOptions(
            name='appconfig',
            options={'verbose_name': 'Бот', 'verbose_name_plural': 'Боты'},
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='api_id',
            field=models.CharField(blank=True, default=None, help_text='getting from https://my.telegram.org/auth', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='auth_users',
            field=models.CharField(blank=True, default='261336294 448374494', help_text='authenticated users for bot using', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='appconfig',
            name='is_bot',
            field=models.BooleanField(default=True, help_text='select if you want to use bot account for this config', null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ugc.Playlist', verbose_name='Плейлист'),
        ),
    ]
