# Generated by Django 2.2.10 on 2020-02-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0005_auto_20200221_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='categories',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='video',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tg_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Id в телеграме'),
        ),
        migrations.AlterField(
            model_name='video',
            name='upload_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Просмотров'),
        ),
    ]
