# Generated by Django 2.2.10 on 2020-02-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0007_playlist_playlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='playlist_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя проверка'),
        ),
    ]
