# Generated by Django 2.2.10 on 2020-02-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0008_auto_20200221_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tg_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Id в телеграме'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Канал отправителя'),
        ),
        migrations.AlterField(
            model_name='video',
            name='yt_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Id видео'),
        ),
    ]
