# Generated by Django 2.2.10 on 2020-02-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0009_auto_20200221_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип публикации')),
                ('data', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('post_time', models.DateTimeField(blank=True, null=True, verbose_name='Время Публикации')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='hot',
            field=models.FloatField(default=False, verbose_name='Новинка'),
        ),
    ]
