# Generated by Django 2.2.10 on 2020-02-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0011_playlist_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Расписание', 'verbose_name_plural': 'Расписания'},
        ),
        migrations.AddField(
            model_name='appconfig',
            name='client_code',
            field=models.CharField(blank=True, default=None, help_text='Код авторизации.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appconfig',
            name='client_phone',
            field=models.CharField(blank=True, default=None, help_text='Телефон аккаунта, с которого загружаются видео для авторизации.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=False, null=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='message',
            field=models.TextField(blank=True, help_text='Сообщение в markdown формате. https://core.telegram.org/bots/api#markdown-style', null=True, verbose_name='Текст описания'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='active',
            field=models.BooleanField(default=False, null=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='data',
            field=models.TextField(blank=True, help_text='Video: youtube id или несколько (через пробел) видео из нашей базы. Message: оставить пустым. Image: ссылка или несколько на изображение', null=True, verbose_name='Данные'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='post_type',
            field=models.CharField(blank=True, choices=[('msg', 'Message'), ('vid', 'Video'), ('im', 'Image')], max_length=255, null=True, verbose_name='Тип публикации'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hot',
            field=models.BooleanField(default=False, null=True, verbose_name='Новинка'),
        ),
    ]
