# Generated by Django 2.2.10 on 2020-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ugc', '0012_auto_20200222_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='post_type',
            field=models.CharField(blank=True, choices=[('msg', 'message'), ('vid', 'video'), ('im', 'image')], help_text='Пока что работает только video. Казать только поле данные', max_length=255, null=True, verbose_name='Тип публикации'),
        ),
    ]
